# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy Backend to Azure Web App - Coffee-Bean-Roast-Level-Detector

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkou

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for faster checkout
          submodules: false # Disable submodules unless yolov5/ is a submodule

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Matches Azure Web App runtime (PYTHON|3.8)

      - name: Verify requirements file
        run: |
          ls -l backend/requirements.txt
          ls -l backend/yolov5/requirements.txt || echo "yolov5/requirements.txt not found"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for Azure login
      contents: read # Required for actions/download-artifact

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B933DF00DB884C7383649870A911BB63 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_62434904970240718A02319B41A3BC4A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BDAFA5E0452C4EB68C1D6B5437B471C9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Coffee-Bean-Roast-Level-Detector' # Matches Azure Web App name
          slot-name: 'Production'
